// ─── World city dataset for astrocartography skylines ─────────────────────────
// ~165 cities. Iconic cities carry an authored `landmark` profile; the rest
// render a deterministic data-driven procedural skyline keyed off height/density.

import type { LandmarkId } from "./skylines";

export type Region = "Americas" | "Europe" | "Africa-ME" | "Asia" | "Oceania";

export interface City {
  name: string;
  lat: number;
  lon: number;
  region: Region;
  /** skyline height bucket 0=low 1=mid 2=high 3=supertall */
  height: 0 | 1 | 2 | 3;
  /** density bucket 0=sparse 1=medium 2=dense */
  density: 0 | 1 | 2;
  /** authored landmark profile; when absent the city is procedural */
  landmark?: LandmarkId;
}

const A = "Americas", E = "Europe", AM = "Africa-ME", AS = "Asia", O = "Oceania";

export const CITIES: City[] = [
  // ── Americas ──────────────────────────────────────────────────────────────
  { name: "New York",       lat:  40.71, lon:  -74.01, region: A, height: 3, density: 2, landmark: "newyork" },
  { name: "Los Angeles",    lat:  34.05, lon: -118.24, region: A, height: 2, density: 2, landmark: "losangeles" },
  { name: "San Francisco",  lat:  37.77, lon: -122.42, region: A, height: 2, density: 1, landmark: "sanfrancisco" },
  { name: "Chicago",        lat:  41.88, lon:  -87.63, region: A, height: 3, density: 2, landmark: "chicago" },
  { name: "Toronto",        lat:  43.65, lon:  -79.38, region: A, height: 3, density: 2, landmark: "toronto" },
  { name: "Las Vegas",      lat:  36.17, lon: -115.14, region: A, height: 2, density: 1, landmark: "lasvegas" },
  { name: "Seattle",        lat:  47.61, lon: -122.33, region: A, height: 2, density: 1, landmark: "seattle" },
  { name: "Miami",          lat:  25.76, lon:  -80.19, region: A, height: 2, density: 2 },
  { name: "Houston",        lat:  29.76, lon:  -95.37, region: A, height: 2, density: 1 },
  { name: "Dallas",         lat:  32.78, lon:  -96.80, region: A, height: 2, density: 1, landmark: "dallas" },
  { name: "Atlanta",        lat:  33.75, lon:  -84.39, region: A, height: 2, density: 1 },
  { name: "Boston",         lat:  42.36, lon:  -71.06, region: A, height: 2, density: 1 },
  { name: "Washington DC",  lat:  38.91, lon:  -77.04, region: A, height: 1, density: 1 },
  { name: "Philadelphia",   lat:  39.95, lon:  -75.17, region: A, height: 2, density: 1 },
  { name: "Denver",         lat:  39.74, lon: -104.98, region: A, height: 1, density: 1 },
  { name: "Phoenix",        lat:  33.45, lon: -112.07, region: A, height: 1, density: 1 },
  { name: "Nashville",      lat:  36.17, lon:  -86.78, region: A, height: 1, density: 0 },
  { name: "Minneapolis",    lat:  44.98, lon:  -93.27, region: A, height: 1, density: 1 },
  { name: "San Diego",      lat:  32.72, lon: -117.16, region: A, height: 1, density: 1 },
  { name: "Austin",         lat:  30.27, lon:  -97.74, region: A, height: 1, density: 1 },
  { name: "Vancouver",      lat:  49.28, lon: -123.12, region: A, height: 2, density: 1 },
  { name: "Montreal",       lat:  45.50, lon:  -73.57, region: A, height: 1, density: 1 },
  { name: "Mexico City",    lat:  19.43, lon:  -99.13, region: A, height: 2, density: 2 },
  { name: "Monterrey",      lat:  25.69, lon: -100.32, region: A, height: 1, density: 1, landmark: "monterrey" },
  { name: "Guadalajara",    lat:  20.66, lon: -103.35, region: A, height: 1, density: 1 },
  { name: "Havana",         lat:  23.11, lon:  -82.37, region: A, height: 0, density: 1 },
  { name: "Panama City",    lat:   8.98, lon:  -79.52, region: A, height: 2, density: 1 },
  { name: "Bogotá",         lat:   4.71, lon:  -74.07, region: A, height: 1, density: 2, landmark: "bogota" },
  { name: "Medellín",       lat:   6.24, lon:  -75.58, region: A, height: 1, density: 1 },
  { name: "Lima",           lat: -12.05, lon:  -77.04, region: A, height: 1, density: 2, landmark: "lima" },
  { name: "Quito",          lat:  -0.18, lon:  -78.47, region: A, height: 1, density: 1 },
  { name: "Caracas",        lat:  10.49, lon:  -66.88, region: A, height: 1, density: 2 },
  { name: "Santiago",       lat: -33.45, lon:  -70.67, region: A, height: 2, density: 1 },
  { name: "Buenos Aires",   lat: -34.60, lon:  -58.38, region: A, height: 2, density: 2, landmark: "buenos_aires" },
  { name: "São Paulo",      lat: -23.55, lon:  -46.63, region: A, height: 2, density: 2 },
  { name: "Rio de Janeiro", lat: -22.91, lon:  -43.17, region: A, height: 2, density: 2 },
  { name: "Brasília",       lat: -15.79, lon:  -47.88, region: A, height: 1, density: 0 },
  { name: "Montevideo",     lat: -34.90, lon:  -56.16, region: A, height: 1, density: 1 },
  { name: "Cartagena",      lat:  10.39, lon:  -75.51, region: A, height: 1, density: 1 },

  // ── Europe ────────────────────────────────────────────────────────────────
  { name: "London",         lat:  51.51, lon:   -0.13, region: E, height: 3, density: 2, landmark: "london" },
  { name: "Paris",          lat:  48.85, lon:    2.35, region: E, height: 2, density: 2, landmark: "paris" },
  { name: "Moscow",         lat:  55.75, lon:   37.62, region: E, height: 3, density: 2, landmark: "moscow" },
  { name: "Rome",           lat:  41.90, lon:   12.50, region: E, height: 1, density: 1, landmark: "rome" },
  { name: "Berlin",         lat:  52.52, lon:   13.41, region: E, height: 2, density: 1, landmark: "berlin" },
  { name: "Barcelona",      lat:  41.38, lon:    2.17, region: E, height: 1, density: 2, landmark: "barcelona" },
  { name: "Frankfurt",      lat:  50.11, lon:    8.68, region: E, height: 3, density: 1, landmark: "frankfurt" },
  { name: "Madrid",         lat:  40.42, lon:   -3.70, region: E, height: 2, density: 2 },
  { name: "Amsterdam",      lat:  52.37, lon:    4.90, region: E, height: 1, density: 1 },
  { name: "Milan",          lat:  45.46, lon:    9.19, region: E, height: 2, density: 2 },
  { name: "Vienna",         lat:  48.21, lon:   16.37, region: E, height: 1, density: 1 },
  { name: "Prague",         lat:  50.08, lon:   14.44, region: E, height: 1, density: 1 },
  { name: "Warsaw",         lat:  52.23, lon:   21.01, region: E, height: 2, density: 1 },
  { name: "Lisbon",         lat:  38.72, lon:   -9.14, region: E, height: 1, density: 1 },
  { name: "Brussels",       lat:  50.85, lon:    4.35, region: E, height: 1, density: 1 },
  { name: "Munich",         lat:  48.14, lon:   11.58, region: E, height: 1, density: 1 },
  { name: "Hamburg",        lat:  53.55, lon:    9.99, region: E, height: 1, density: 1 },
  { name: "Zürich",         lat:  47.37, lon:    8.54, region: E, height: 1, density: 1 },
  { name: "Geneva",         lat:  46.20, lon:    6.14, region: E, height: 1, density: 0 },
  { name: "Dublin",         lat:  53.35, lon:   -6.26, region: E, height: 1, density: 1 },
  { name: "Edinburgh",      lat:  55.95, lon:   -3.19, region: E, height: 0, density: 1 },
  { name: "Manchester",     lat:  53.48, lon:   -2.24, region: E, height: 1, density: 1 },
  { name: "Stockholm",      lat:  59.33, lon:   18.07, region: E, height: 1, density: 1 },
  { name: "Oslo",           lat:  59.91, lon:   10.75, region: E, height: 1, density: 1 },
  { name: "Copenhagen",     lat:  55.68, lon:   12.57, region: E, height: 1, density: 1 },
  { name: "Helsinki",       lat:  60.17, lon:   24.94, region: E, height: 1, density: 1 },
  { name: "Reykjavik",      lat:  64.13, lon:  -21.94, region: E, height: 0, density: 0 },
  { name: "Athens",         lat:  37.98, lon:   23.73, region: E, height: 1, density: 2, landmark: "athens" },
  { name: "Budapest",       lat:  47.50, lon:   19.04, region: E, height: 1, density: 1 },
  { name: "Bucharest",      lat:  44.43, lon:   26.10, region: E, height: 1, density: 1 },
  { name: "Kyiv",           lat:  50.45, lon:   30.52, region: E, height: 1, density: 1 },
  { name: "Saint Petersburg", lat: 59.93, lon:  30.34, region: E, height: 1, density: 1 },
  { name: "Naples",         lat:  40.85, lon:   14.27, region: E, height: 1, density: 2 },
  { name: "Venice",         lat:  45.44, lon:   12.32, region: E, height: 0, density: 1 },

  // ── Africa & Middle East ────────────────────────────────────────────────────
  { name: "Dubai",          lat:  25.20, lon:   55.27, region: AM, height: 3, density: 2, landmark: "dubai" },
  { name: "Abu Dhabi",      lat:  24.45, lon:   54.38, region: AM, height: 3, density: 1, landmark: "abudhabi" },
  { name: "Doha",           lat:  25.29, lon:   51.53, region: AM, height: 3, density: 1, landmark: "doha" },
  { name: "Riyadh",         lat:  24.69, lon:   46.72, region: AM, height: 3, density: 1, landmark: "riyadh" },
  { name: "Istanbul",       lat:  41.01, lon:   28.98, region: AM, height: 2, density: 2, landmark: "istanbul" },
  { name: "Cairo",          lat:  30.04, lon:   31.24, region: AM, height: 1, density: 2, landmark: "cairo" },
  { name: "Tel Aviv",       lat:  32.08, lon:   34.78, region: AM, height: 2, density: 2 },
  { name: "Jerusalem",      lat:  31.77, lon:   35.21, region: AM, height: 1, density: 1 },
  { name: "Jeddah",         lat:  21.49, lon:   39.19, region: AM, height: 2, density: 1 },
  { name: "Kuwait City",    lat:  29.38, lon:   47.99, region: AM, height: 2, density: 1 },
  { name: "Manama",         lat:  26.23, lon:   50.59, region: AM, height: 2, density: 1 },
  { name: "Muscat",         lat:  23.59, lon:   58.41, region: AM, height: 1, density: 1 },
  { name: "Amman",          lat:  31.95, lon:   35.93, region: AM, height: 1, density: 1 },
  { name: "Beirut",         lat:  33.89, lon:   35.50, region: AM, height: 1, density: 2 },
  { name: "Tehran",         lat:  35.69, lon:   51.39, region: AM, height: 1, density: 2 },
  { name: "Baghdad",        lat:  33.31, lon:   44.36, region: AM, height: 1, density: 2 },
  { name: "Casablanca",     lat:  33.57, lon:   -7.59, region: AM, height: 1, density: 2 },
  { name: "Marrakech",      lat:  31.63, lon:   -7.99, region: AM, height: 0, density: 1 },
  { name: "Tunis",          lat:  36.81, lon:   10.18, region: AM, height: 1, density: 1 },
  { name: "Lagos",          lat:   6.52, lon:    3.38, region: AM, height: 1, density: 2, landmark: "lagos" },
  { name: "Accra",          lat:   5.60, lon:   -0.19, region: AM, height: 1, density: 1 },
  { name: "Nairobi",        lat:  -1.29, lon:   36.82, region: AM, height: 1, density: 1, landmark: "nairobi" },
  { name: "Addis Ababa",    lat:   9.03, lon:   38.74, region: AM, height: 1, density: 1 },
  { name: "Dakar",          lat:  14.69, lon:  -17.45, region: AM, height: 1, density: 1 },
  { name: "Johannesburg",   lat: -26.20, lon:   28.04, region: AM, height: 2, density: 2, landmark: "johannesburg" },
  { name: "Cape Town",      lat: -33.92, lon:   18.42, region: AM, height: 1, density: 1 },
  { name: "Durban",         lat: -29.86, lon:   31.03, region: AM, height: 1, density: 1 },
  { name: "Luanda",         lat:  -8.84, lon:   13.23, region: AM, height: 1, density: 1 },

  // ── Asia ────────────────────────────────────────────────────────────────────
  { name: "Tokyo",          lat:  35.68, lon:  139.69, region: AS, height: 3, density: 2, landmark: "tokyo" },
  { name: "Shanghai",       lat:  31.23, lon:  121.47, region: AS, height: 3, density: 2, landmark: "shanghai" },
  { name: "Hong Kong",      lat:  22.32, lon:  114.17, region: AS, height: 3, density: 2, landmark: "hongkong" },
  { name: "Singapore",      lat:   1.35, lon:  103.82, region: AS, height: 3, density: 2, landmark: "singapore" },
  { name: "Kuala Lumpur",   lat:   3.14, lon:  101.69, region: AS, height: 3, density: 2, landmark: "kualalumpur" },
  { name: "Beijing",        lat:  39.90, lon:  116.41, region: AS, height: 3, density: 2, landmark: "beijing" },
  { name: "Seoul",          lat:  37.57, lon:  126.98, region: AS, height: 3, density: 2 },
  { name: "Osaka",          lat:  34.69, lon:  135.50, region: AS, height: 2, density: 2 },
  { name: "Nagoya",         lat:  35.18, lon:  136.91, region: AS, height: 2, density: 2 },
  { name: "Sapporo",        lat:  43.06, lon:  141.35, region: AS, height: 1, density: 1 },
  { name: "Shenzhen",       lat:  22.54, lon:  114.06, region: AS, height: 3, density: 2 },
  { name: "Guangzhou",      lat:  23.13, lon:  113.26, region: AS, height: 3, density: 2 },
  { name: "Chengdu",        lat:  30.57, lon:  104.07, region: AS, height: 2, density: 2 },
  { name: "Chongqing",      lat:  29.56, lon:  106.55, region: AS, height: 3, density: 2 },
  { name: "Wuhan",          lat:  30.59, lon:  114.31, region: AS, height: 2, density: 2 },
  { name: "Taipei",         lat:  25.03, lon:  121.57, region: AS, height: 3, density: 2 },
  { name: "Bangkok",        lat:  13.76, lon:  100.50, region: AS, height: 2, density: 2 },
  { name: "Jakarta",        lat:  -6.21, lon:  106.85, region: AS, height: 2, density: 2 },
  { name: "Manila",         lat:  14.60, lon:  120.98, region: AS, height: 2, density: 2 },
  { name: "Ho Chi Minh City", lat: 10.82, lon: 106.63, region: AS, height: 2, density: 2 },
  { name: "Hanoi",          lat:  21.03, lon:  105.85, region: AS, height: 1, density: 2 },
  { name: "Bali",           lat:  -8.34, lon:  115.09, region: AS, height: 0, density: 0 },
  { name: "Mumbai",         lat:  19.08, lon:   72.88, region: AS, height: 2, density: 2, landmark: "mumbai" },
  { name: "Delhi",          lat:  28.66, lon:   77.22, region: AS, height: 1, density: 2 },
  { name: "Bengaluru",      lat:  12.97, lon:   77.59, region: AS, height: 1, density: 2 },
  { name: "Chennai",        lat:  13.08, lon:   80.27, region: AS, height: 1, density: 2 },
  { name: "Hyderabad",      lat:  17.39, lon:   78.49, region: AS, height: 1, density: 2 },
  { name: "Kolkata",        lat:  22.57, lon:   88.36, region: AS, height: 1, density: 2 },
  { name: "Karachi",        lat:  24.86, lon:   67.01, region: AS, height: 1, density: 2 },
  { name: "Lahore",         lat:  31.55, lon:   74.34, region: AS, height: 1, density: 2 },
  { name: "Dhaka",          lat:  23.81, lon:   90.41, region: AS, height: 1, density: 2 },
  { name: "Colombo",        lat:   6.93, lon:   79.86, region: AS, height: 1, density: 1 },
  { name: "Kathmandu",      lat:  27.72, lon:   85.32, region: AS, height: 0, density: 1 },
  { name: "Ulaanbaatar",    lat:  47.89, lon:  106.91, region: AS, height: 1, density: 1 },
  { name: "Almaty",         lat:  43.24, lon:   76.95, region: AS, height: 1, density: 1 },
  { name: "Tashkent",       lat:  41.30, lon:   69.24, region: AS, height: 1, density: 1 },
  { name: "Baku",           lat:  40.41, lon:   49.87, region: AS, height: 2, density: 1 },

  // ── Oceania ─────────────────────────────────────────────────────────────────
  { name: "Sydney",         lat: -33.87, lon:  151.21, region: O, height: 3, density: 2, landmark: "sydney" },
  { name: "Melbourne",      lat: -37.81, lon:  144.96, region: O, height: 3, density: 2 },
  { name: "Brisbane",       lat: -27.47, lon:  153.03, region: O, height: 2, density: 1 },
  { name: "Perth",          lat: -31.95, lon:  115.86, region: O, height: 2, density: 1 },
  { name: "Adelaide",       lat: -34.93, lon:  138.60, region: O, height: 1, density: 1 },
  { name: "Gold Coast",     lat: -28.02, lon:  153.40, region: O, height: 2, density: 1 },
  { name: "Auckland",       lat: -36.85, lon:  174.76, region: O, height: 2, density: 1 },
  { name: "Wellington",     lat: -41.29, lon:  174.78, region: O, height: 1, density: 1, landmark: "wellington" },
  { name: "Honolulu",       lat:  21.31, lon: -157.86, region: O, height: 1, density: 1 },
  { name: "Suva",           lat: -18.14, lon:  178.44, region: O, height: 0, density: 0 },
  { name: "Port Moresby",   lat:  -9.44, lon:  147.18, region: O, height: 0, density: 0 },
  { name: "Nouméa",         lat: -22.28, lon:  166.46, region: O, height: 0, density: 0 },
];
