import type { AkashicEntry } from "./types";

export const AKASHIC_ENTRIES: AkashicEntry[] = [

  // ─── FOUNDATIONS: PLANETS ────────────────────────────────────────────────────

  {
    slug: "planet-sun", title: "The Sun", subtitle: "☉ · Identity · Will · Vitality",
    category: "foundations", tags: ["planet", "luminary", "fire", "ego"],
    summary: "The Sun is the core of your conscious identity — the will-power, the ego, and the creative life force that animates your entire chart. It describes where you must shine, the role you are meant to play, and the central theme of this lifetime.",
    chartKeys: [{ type: "planet", name: "Sun" }],
    relatedSlugs: ["house-5th", "sign-leo", "hellenistic-sect", "hellenistic-lot-spirit"],
    promptHint: "Sun in astrology: identity, vitality, the hero myth, Leo rulership, sect importance in Hellenistic, Surya in Jyotish, solar returns as the yearly chapter.",
  },
  {
    slug: "planet-moon", title: "The Moon", subtitle: "☽ · Soul · Emotion · The Body",
    category: "foundations", tags: ["planet", "luminary", "water", "emotion"],
    summary: "The Moon governs your inner world — the habitual emotional responses, the body's instincts, memory, and the quality of your daily felt experience. It is the planet most tied to childhood conditioning and your relationship with safety, nurturing, and belonging.",
    chartKeys: [{ type: "planet", name: "Moon" }],
    relatedSlugs: ["house-4th", "sign-cancer", "vedic-nakshatra", "vedic-vimshottari-dasha"],
    promptHint: "Moon in astrology: emotion, memory, instinct, the mother archetype, Hellenistic sect luminary for night charts, Chandra in Jyotish, nakshatra placement as soul fingerprint.",
  },
  {
    slug: "planet-mercury", title: "Mercury", subtitle: "☿ · Mind · Language · Perception",
    category: "foundations", tags: ["planet", "air", "earth", "communication"],
    summary: "Mercury rules the way you think, speak, and process information — the nervous system of the chart. It describes your mental style, the tone of your communication, and how you connect ideas, people, and places.",
    chartKeys: [{ type: "planet", name: "Mercury" }],
    relatedSlugs: ["house-3rd", "house-6th", "sign-gemini", "sign-virgo"],
    promptHint: "Mercury: cognition, language, trade, siblings, the messenger archetype, Gemini/Virgo rulership, Budha in Jyotish, retrograde cycles and their re-examination themes.",
  },
  {
    slug: "planet-venus", title: "Venus", subtitle: "♀ · Love · Beauty · Value",
    category: "foundations", tags: ["planet", "air", "earth", "relationship"],
    summary: "Venus describes what you love and how you love — your aesthetic sensibility, your values, your capacity for pleasure and connection. It governs both romance and money as expressions of what you find worth having.",
    chartKeys: [{ type: "planet", name: "Venus" }],
    relatedSlugs: ["house-2nd", "house-7th", "sign-taurus", "sign-libra", "hellenistic-lot-fortune"],
    promptHint: "Venus: love, beauty, resources, Aphrodite archetype, Taurus/Libra rulership, Shukra in Jyotish, evening/morning star sect distinction, relationship to the Lot of Fortune.",
  },
  {
    slug: "planet-mars", title: "Mars", subtitle: "♂ · Drive · Conflict · Courage",
    category: "foundations", tags: ["planet", "fire", "water", "will"],
    summary: "Mars is the engine of desire and the seat of courage — it describes how you assert yourself, what you fight for, and where you direct raw energy. Its placement reveals your relationship with anger, ambition, and physical vitality.",
    chartKeys: [{ type: "planet", name: "Mars" }],
    relatedSlugs: ["house-1st", "house-8th", "sign-aries", "sign-scorpio"],
    promptHint: "Mars: will, aggression, courage, Ares archetype, Aries/Scorpio traditional rulership, Mangala in Jyotish, malefic by nature but beneficial for action, retrograde cycles.",
  },
  {
    slug: "planet-jupiter", title: "Jupiter", subtitle: "♃ · Expansion · Wisdom · Grace",
    category: "foundations", tags: ["planet", "fire", "water", "benefic"],
    summary: "Jupiter is the great benefic — it expands, blesses, and brings opportunities wherever it touches. It describes your philosophy of life, your faith, your capacity for abundance, and where the universe seems to open doors for you.",
    chartKeys: [{ type: "planet", name: "Jupiter" }],
    relatedSlugs: ["house-9th", "house-12th", "sign-sagittarius", "sign-pisces"],
    promptHint: "Jupiter: expansion, wisdom, faith, Zeus/Guru archetype, Sagittarius/Pisces rulership, Brihaspati in Jyotish, great benefic in Hellenistic tradition, transit cycles of 12 years.",
  },
  {
    slug: "planet-saturn", title: "Saturn", subtitle: "♄ · Time · Structure · Karma",
    category: "foundations", tags: ["planet", "earth", "air", "malefic"],
    summary: "Saturn is the great teacher — demanding, patient, and ultimately rewarding. It describes where you face limitation, responsibility, and the slow building of mastery. What Saturn touches eventually becomes your greatest area of earned authority.",
    chartKeys: [{ type: "planet", name: "Saturn" }],
    relatedSlugs: ["house-10th", "house-11th", "sign-capricorn", "sign-aquarius", "timing-firdaria"],
    promptHint: "Saturn: time, restriction, karma, Cronus archetype, Capricorn/Aquarius rulership, Shani in Jyotish, malefic benefiting from sect, 29.5-year return, Saturn dasha as crucible.",
  },
  {
    slug: "planet-uranus", title: "Uranus", subtitle: "⛢ · Revolution · Genius · Liberation",
    category: "foundations", tags: ["planet", "air", "outer", "modern"],
    summary: "Uranus rules the sudden break, the flash of insight, and the irresistible urge to be free. Its house and sign describe where conventional rules feel like a cage, and where your genius — or your chaos — breaks through.",
    chartKeys: [{ type: "planet", name: "Uranus" }],
    relatedSlugs: ["sign-aquarius", "house-11th"],
    promptHint: "Uranus: revolution, electrical disruption, the trickster/inventor, modern rulership of Aquarius, generational influence, Uranus oppositions and mid-life crises.",
  },
  {
    slug: "planet-neptune", title: "Neptune", subtitle: "♆ · Dreams · Dissolution · Spirit",
    category: "foundations", tags: ["planet", "water", "outer", "modern"],
    summary: "Neptune dissolves boundaries — between self and other, real and imagined, sacred and ordinary. Its house and sign describe where you seek transcendence, where illusion is most potent, and where compassion or confusion can run deepest.",
    chartKeys: [{ type: "planet", name: "Neptune" }],
    relatedSlugs: ["sign-pisces", "house-12th"],
    promptHint: "Neptune: dissolution, mysticism, addiction, modern rulership of Pisces, the veil between worlds, Neptune conjunctions as generation-defining spiritual openings.",
  },
  {
    slug: "planet-pluto", title: "Pluto", subtitle: "♇ · Death · Power · Transformation",
    category: "foundations", tags: ["planet", "water", "outer", "modern"],
    summary: "Pluto rules radical transformation through death and rebirth. Its house and sign describe where power dynamics, compulsion, and irreversible change operate — the place in your chart where you go into the underworld and emerge changed.",
    chartKeys: [{ type: "planet", name: "Pluto" }],
    relatedSlugs: ["sign-scorpio", "house-8th"],
    promptHint: "Pluto: Hades archetype, generational power shifts, compulsion and obsession, modern co-rulership of Scorpio, Pluto conjunctions as era-defining upheavals.",
  },

  // ─── FOUNDATIONS: SIGNS ──────────────────────────────────────────────────────

  {
    slug: "sign-aries", title: "Aries", subtitle: "♈ · Cardinal Fire · The Ram",
    category: "foundations", tags: ["sign", "fire", "cardinal", "mars"],
    summary: "Aries is the first spark of existence — raw initiative, courage, and the primal need to act. Planets here are impulsive, direct, and driven to pioneer, often learning through trial and error.",
    chartKeys: [{ type: "sign", name: "Aries" }],
    relatedSlugs: ["planet-mars", "house-1st", "sign-libra"],
    promptHint: "Aries: cardinal fire, first sign, Mars-ruled, spring equinox, identity through action, the warrior archetype, Mesha in Jyotish.",
  },
  {
    slug: "sign-taurus", title: "Taurus", subtitle: "♉ · Fixed Earth · The Bull",
    category: "foundations", tags: ["sign", "earth", "fixed", "venus"],
    summary: "Taurus values stability, embodied pleasure, and the slow accumulation of what endures. Planets here build steadily, resist change, and seek to ground the intangible into something real, beautiful, and lasting.",
    chartKeys: [{ type: "sign", name: "Taurus" }],
    relatedSlugs: ["planet-venus", "house-2nd", "sign-scorpio"],
    promptHint: "Taurus: fixed earth, Venus-ruled, sensory pleasure, resource building, the artisan and farmer archetype, Vrishabha in Jyotish.",
  },
  {
    slug: "sign-gemini", title: "Gemini", subtitle: "♊ · Mutable Air · The Twins",
    category: "foundations", tags: ["sign", "air", "mutable", "mercury"],
    summary: "Gemini is the sign of the eternal student — curious, quick, and endlessly fascinated by the diversity of information and people. Planets here are versatile, talkative, and prone to seeing multiple sides of every question.",
    chartKeys: [{ type: "sign", name: "Gemini" }],
    relatedSlugs: ["planet-mercury", "house-3rd", "sign-sagittarius"],
    promptHint: "Gemini: mutable air, Mercury-ruled, duality and multiplicity, communication and commerce, the trickster and messenger, Mithuna in Jyotish.",
  },
  {
    slug: "sign-cancer", title: "Cancer", subtitle: "♋ · Cardinal Water · The Crab",
    category: "foundations", tags: ["sign", "water", "cardinal", "moon"],
    summary: "Cancer is the sign of roots, memory, and emotional safety. Planets here operate through feeling and instinct, building protective shells around what is most precious — home, family, and the continuity of the past.",
    chartKeys: [{ type: "sign", name: "Cancer" }],
    relatedSlugs: ["planet-moon", "house-4th", "sign-capricorn"],
    promptHint: "Cancer: cardinal water, Moon-ruled, home and family, protective instincts, the mother archetype and the ancestral memory, Karka in Jyotish.",
  },
  {
    slug: "sign-leo", title: "Leo", subtitle: "♌ · Fixed Fire · The Lion",
    category: "foundations", tags: ["sign", "fire", "fixed", "sun"],
    summary: "Leo is the sign of self-expression, creativity, and the will to be seen. Planets here burn brightly, crave recognition, and operate through dramatic flair — they must create, lead, or perform to feel fully alive.",
    chartKeys: [{ type: "sign", name: "Leo" }],
    relatedSlugs: ["planet-sun", "house-5th", "sign-aquarius"],
    promptHint: "Leo: fixed fire, Sun-ruled, the king/queen archetype, creative self-expression, pride and generosity, children and play, Simha in Jyotish.",
  },
  {
    slug: "sign-virgo", title: "Virgo", subtitle: "♍ · Mutable Earth · The Virgin",
    category: "foundations", tags: ["sign", "earth", "mutable", "mercury"],
    summary: "Virgo is the sign of discernment, craft, and devoted service. Planets here analyze, refine, and improve — they are drawn to the work that needs doing and the flaw that needs correcting, often learning to find the sacred in the ordinary.",
    chartKeys: [{ type: "sign", name: "Virgo" }],
    relatedSlugs: ["planet-mercury", "house-6th", "sign-pisces"],
    promptHint: "Virgo: mutable earth, Mercury-ruled, analysis and purification, service and health, the healer and craftsperson archetype, Kanya in Jyotish.",
  },
  {
    slug: "sign-libra", title: "Libra", subtitle: "♎ · Cardinal Air · The Scales",
    category: "foundations", tags: ["sign", "air", "cardinal", "venus"],
    summary: "Libra is the sign of relationship, fairness, and the art of finding equilibrium between opposing forces. Planets here operate through partnership and comparison, endlessly weighing what is just, beautiful, or socially harmonious.",
    chartKeys: [{ type: "sign", name: "Libra" }],
    relatedSlugs: ["planet-venus", "house-7th", "sign-aries"],
    promptHint: "Libra: cardinal air, Venus-ruled, justice and balance, the diplomat and aesthete, partnership as the mirror of self, Tula in Jyotish.",
  },
  {
    slug: "sign-scorpio", title: "Scorpio", subtitle: "♏ · Fixed Water · The Scorpion",
    category: "foundations", tags: ["sign", "water", "fixed", "mars", "pluto"],
    summary: "Scorpio is the sign of depth, power, and transformative intensity. Planets here are drawn to the hidden, the taboo, and the irreversible — they want to see what lies beneath the surface, and are willing to go through death to find it.",
    chartKeys: [{ type: "sign", name: "Scorpio" }],
    relatedSlugs: ["planet-mars", "planet-pluto", "house-8th", "sign-taurus"],
    promptHint: "Scorpio: fixed water, Mars (traditional) and Pluto (modern) ruled, depth and transformation, the detective and shaman, sexual and occult themes, Vrishchika in Jyotish.",
  },
  {
    slug: "sign-sagittarius", title: "Sagittarius", subtitle: "♐ · Mutable Fire · The Archer",
    category: "foundations", tags: ["sign", "fire", "mutable", "jupiter"],
    summary: "Sagittarius is the sign of the philosopher and the adventurer — always seeking the horizon, the meaning behind the event, and the bigger picture. Planets here are expansive, optimistic, and restless for truth.",
    chartKeys: [{ type: "sign", name: "Sagittarius" }],
    relatedSlugs: ["planet-jupiter", "house-9th", "sign-gemini"],
    promptHint: "Sagittarius: mutable fire, Jupiter-ruled, philosophy and long journeys, the archer aiming at truth, higher education and faith, Dhanus in Jyotish.",
  },
  {
    slug: "sign-capricorn", title: "Capricorn", subtitle: "♑ · Cardinal Earth · The Sea-Goat",
    category: "foundations", tags: ["sign", "earth", "cardinal", "saturn"],
    summary: "Capricorn is the sign of ambition, mastery, and the patient climb toward authority. Planets here work hard, take the long view, and derive their greatest satisfaction from earned achievement and lasting structures.",
    chartKeys: [{ type: "sign", name: "Capricorn" }],
    relatedSlugs: ["planet-saturn", "house-10th", "sign-cancer"],
    promptHint: "Capricorn: cardinal earth, Saturn-ruled, ambition and career, the elder/patriarch archetype, time and patience as virtues, Makara in Jyotish.",
  },
  {
    slug: "sign-aquarius", title: "Aquarius", subtitle: "♒ · Fixed Air · The Water Bearer",
    category: "foundations", tags: ["sign", "air", "fixed", "saturn", "uranus"],
    summary: "Aquarius is the sign of the collective, the future, and the radical idea. Planets here operate through community, innovation, and a stubborn commitment to what ought to be — often ahead of their time, sometimes alienated from the present.",
    chartKeys: [{ type: "sign", name: "Aquarius" }],
    relatedSlugs: ["planet-saturn", "planet-uranus", "house-11th", "sign-leo"],
    promptHint: "Aquarius: fixed air, Saturn (traditional) and Uranus (modern) ruled, the visionary and revolutionary, humanitarian ideals, groups and societies, Kumbha in Jyotish.",
  },
  {
    slug: "sign-pisces", title: "Pisces", subtitle: "♓ · Mutable Water · The Fish",
    category: "foundations", tags: ["sign", "water", "mutable", "jupiter", "neptune"],
    summary: "Pisces is the sign of dissolution, compassion, and mystical receptivity. Planets here move in and out of reality's edges — drawn to the invisible, the sacred, the suffering of others, and the longing to return to oneness.",
    chartKeys: [{ type: "sign", name: "Pisces" }],
    relatedSlugs: ["planet-jupiter", "planet-neptune", "house-12th", "sign-virgo"],
    promptHint: "Pisces: mutable water, Jupiter (traditional) and Neptune (modern) ruled, the mystic and martyr, dissolution of ego, compassion and escapism, Meena in Jyotish.",
  },

  // ─── FOUNDATIONS: HOUSES ─────────────────────────────────────────────────────

  {
    slug: "house-1st", title: "The First House", subtitle: "Lagna · Identity · The Body",
    category: "foundations", tags: ["house", "angular", "self"],
    summary: "The First House is who you are before you say a word — the body, the face you show the world, and the first impression you create. Planets here color your entire personality and are felt immediately by everyone you meet.",
    chartKeys: [{ type: "house", number: 1 }],
    relatedSlugs: ["sign-aries", "planet-mars", "hellenistic-sect"],
    promptHint: "1st house: ascendant, rising sign, the body, first impressions, physical vitality, life force, how the soul enters the world, angular power.",
  },
  {
    slug: "house-2nd", title: "The Second House", subtitle: "Resources · Values · Voice",
    category: "foundations", tags: ["house", "succedent", "money"],
    summary: "The Second House rules what you own, what you earn, and what you value — including your own self-worth. It also governs the voice and the throat, the body's resource of sound.",
    chartKeys: [{ type: "house", number: 2 }],
    relatedSlugs: ["sign-taurus", "planet-venus", "hellenistic-lot-fortune"],
    promptHint: "2nd house: personal finances, possessions, self-worth, the voice and throat, moveable resources, what you can call your own.",
  },
  {
    slug: "house-3rd", title: "The Third House", subtitle: "Communication · Siblings · Local World",
    category: "foundations", tags: ["house", "cadent", "communication"],
    summary: "The Third House governs the immediate environment — siblings, short journeys, everyday communication, and the mind as it processes the nearby world. It is the house of the neighborhood, the inbox, and the nervous chatter of daily life.",
    chartKeys: [{ type: "house", number: 3 }],
    relatedSlugs: ["sign-gemini", "planet-mercury"],
    promptHint: "3rd house: siblings, short journeys, writing, communication, local environment, the everyday rational mind, hands and arms.",
  },
  {
    slug: "house-4th", title: "The Fourth House", subtitle: "Home · Roots · The Private Self",
    category: "foundations", tags: ["house", "angular", "family"],
    summary: "The Fourth House is the foundation — the home you grew up in, the parents and ancestors who shaped you, and the private sanctuary you return to at the end of the day. It is the psychological bedrock of the entire chart.",
    chartKeys: [{ type: "house", number: 4 }],
    relatedSlugs: ["sign-cancer", "planet-moon"],
    promptHint: "4th house: home, family, the 4th angle (IC), roots and ancestry, the private life, property and land, the father (in some traditions).",
  },
  {
    slug: "house-5th", title: "The Fifth House", subtitle: "Joy · Creativity · Romance",
    category: "foundations", tags: ["house", "succedent", "pleasure"],
    summary: "The Fifth House is where you play — creativity, romance, children, gambling, and all the activities pursued purely for joy. Planets here describe how you express your heart, what makes you come alive, and the kind of love affairs that light you up.",
    chartKeys: [{ type: "house", number: 5 }],
    relatedSlugs: ["sign-leo", "planet-sun"],
    promptHint: "5th house: creativity, romance, children, pleasure, gambling and speculation, performance, the heart's delight, Leo's natural domain.",
  },
  {
    slug: "house-6th", title: "The Sixth House", subtitle: "Work · Health · Service",
    category: "foundations", tags: ["house", "cadent", "health"],
    summary: "The Sixth House governs the daily grind — work routines, health practices, and service to others. It is where body and schedule meet: how you maintain yourself physically, and the day-to-day labor through which you build skill.",
    chartKeys: [{ type: "house", number: 6 }],
    relatedSlugs: ["sign-virgo", "planet-mercury"],
    promptHint: "6th house: health and illness, daily work, employees and servants, small animals, routines, the body's maintenance, Virgo's natural domain.",
  },
  {
    slug: "house-7th", title: "The Seventh House", subtitle: "Partnership · The Other · Contracts",
    category: "foundations", tags: ["house", "angular", "relationship"],
    summary: "The Seventh House is the mirror — the committed partner, the open enemy, the contract, and the other person in any significant one-on-one dynamic. Planets here describe who you attract and what you seek in relationship.",
    chartKeys: [{ type: "house", number: 7 }],
    relatedSlugs: ["sign-libra", "planet-venus"],
    promptHint: "7th house: marriage and partnership, open enemies, contracts, the descendant angle, what we project onto others, who we attract.",
  },
  {
    slug: "house-8th", title: "The Eighth House", subtitle: "Transformation · Death · Shared Resources",
    category: "foundations", tags: ["house", "succedent", "taboo"],
    summary: "The Eighth House rules the threshold — death, sexuality, inheritance, and the resources you share with others. It is where the ego is most threatened, most tested, and ultimately transformed into something that cannot be taken away.",
    chartKeys: [{ type: "house", number: 8 }],
    relatedSlugs: ["sign-scorpio", "planet-pluto", "planet-mars"],
    promptHint: "8th house: death and rebirth, shared finances, sexuality, occult and hidden matters, legacies and inheritance, transformation through crisis.",
  },
  {
    slug: "house-9th", title: "The Ninth House", subtitle: "Philosophy · Higher Learning · The Divine",
    category: "foundations", tags: ["house", "cadent", "belief"],
    summary: "The Ninth House is where you reach for meaning — through religion, philosophy, long journeys, higher education, and the vast literature of human wisdom. It describes your worldview and what you believe in enough to build your life around.",
    chartKeys: [{ type: "house", number: 9 }],
    relatedSlugs: ["sign-sagittarius", "planet-jupiter"],
    promptHint: "9th house: philosophy and religion, higher education, long travel, publishing, foreigners, the law, the guru, the 9th as the most fortunate cadent house.",
  },
  {
    slug: "house-10th", title: "The Tenth House", subtitle: "Career · Public Life · Legacy",
    category: "foundations", tags: ["house", "angular", "career"],
    summary: "The Tenth House is the highest point of the chart — the public role, the career, the reputation, and the legacy you leave behind. Planets here are visible to the world and describe how you are known, what you build, and the mark you leave.",
    chartKeys: [{ type: "house", number: 10 }],
    relatedSlugs: ["sign-capricorn", "planet-saturn", "vedic-varga-d10"],
    promptHint: "10th house: career, social status, fame, the MC angle (Medium Coeli), authority and ambition, the most elevated planets, Dasamsha D10 in Jyotish.",
  },
  {
    slug: "house-11th", title: "The Eleventh House", subtitle: "Community · Hopes · Networks",
    category: "foundations", tags: ["house", "succedent", "social"],
    summary: "The Eleventh House governs the collective — friends, groups, networks, social movements, and the hopes you hold for the future. It is where individual creativity (5th house) meets the collective response, and where you find your tribe.",
    chartKeys: [{ type: "house", number: 11 }],
    relatedSlugs: ["sign-aquarius", "planet-saturn", "planet-uranus"],
    promptHint: "11th house: friends and allies, hopes and wishes, social groups and networks, gains from career, the joy of Jupiter's natural house, community and collective purpose.",
  },
  {
    slug: "house-12th", title: "The Twelfth House", subtitle: "Hidden · Isolation · Liberation",
    category: "foundations", tags: ["house", "cadent", "spiritual"],
    summary: "The Twelfth House is the place beyond — the unconscious, hidden enemies, isolation, institutions, and ultimately the dissolution of the self into something greater. Planets here operate behind the scenes, accumulating power in secrecy before breaking through.",
    chartKeys: [{ type: "house", number: 12 }],
    relatedSlugs: ["sign-pisces", "planet-neptune", "planet-jupiter"],
    promptHint: "12th house: hidden matters, isolation, retreat, large institutions, undoing and self-undoing, secret enemies, the unconscious, moksha in Jyotish, spiritual liberation.",
  },

  // ─── HELLENISTIC ─────────────────────────────────────────────────────────────

  {
    slug: "hellenistic-sect", title: "Sect", subtitle: "Day Chart · Night Chart · The Fundamental Divide",
    category: "hellenistic", tags: ["hellenistic", "sect", "fundamentals"],
    summary: "Sect is one of the most important distinctions in traditional astrology. Whether you were born during the day or night determines which planets are empowered and which are constrained — it is the first lens through which a classical astrologer reads a chart.",
    chartKeys: [{ type: "technique", key: "sect" }],
    relatedSlugs: ["planet-sun", "planet-moon", "planet-saturn", "planet-jupiter", "planet-mars"],
    promptHint: "Sect: diurnal (day) vs. nocturnal (night) chart, sect luminaries (Sun for day, Moon for night), sect benefics (Jupiter day, Venus night), sect malefics (Saturn day, Mars night), how sect modifies planetary strength.",
  },
  {
    slug: "hellenistic-lot-fortune", title: "Lot of Fortune", subtitle: "☽ · Body · Material Circumstances",
    category: "hellenistic", tags: ["hellenistic", "lots", "arabic-parts"],
    summary: "The Lot of Fortune (Part of Fortune) is the most important of the seven Hermetic Lots — it marks where the Moon's cycle meets the horizon, describing your material circumstances, physical vitality, and the area of life where fortune flows most naturally.",
    chartKeys: [{ type: "planet", name: "Moon" }],
    relatedSlugs: ["hellenistic-lot-spirit", "hellenistic-sect", "planet-moon"],
    promptHint: "Lot of Fortune: ASC + Moon - Sun (day) / ASC + Sun - Moon (night), body and material lot, the lunar principle externalized, house placement significance, ruler of Fortune as material significator.",
  },
  {
    slug: "hellenistic-lot-spirit", title: "Lot of Spirit", subtitle: "☉ · Soul · Deliberate Action",
    category: "hellenistic", tags: ["hellenistic", "lots", "arabic-parts"],
    summary: "The Lot of Spirit is the complement to Fortune — where Fortune describes what happens to you, Spirit describes what you intentionally do. It governs the soul's agency, reputation, and the deliberate choices that shape a life.",
    chartKeys: [{ type: "planet", name: "Sun" }],
    relatedSlugs: ["hellenistic-lot-fortune", "hellenistic-sect", "planet-sun"],
    promptHint: "Lot of Spirit: ASC + Sun - Moon (day) / ASC + Moon - Sun (night), the solar principle externalized, deliberate action and reputation, profession and soul's purpose, ruler of Spirit as spiritual significator.",
  },
  {
    slug: "hellenistic-profections", title: "Annual Profections", subtitle: "One House Per Year · Age-Based Timing",
    category: "hellenistic", tags: ["hellenistic", "timing", "annual"],
    summary: "Annual profections are one of the simplest and most reliable timing tools in traditional astrology. Each year of your life corresponds to one house of your natal chart, cycling from the 1st house at age 0, activating a new house and its ruling planet every birthday.",
    chartKeys: [{ type: "technique", key: "currentDasha" }],
    relatedSlugs: ["hellenistic-sect", "timing-solar-return", "hellenistic-releasing"],
    promptHint: "Annual profections: 12-year cycle, each birthday activates the next house, the Lord of the Year (planet ruling the profected sign) becomes the annual timer, how to find your current profection year by age mod 12.",
  },
  {
    slug: "hellenistic-releasing", title: "Zodiacal Releasing", subtitle: "Planetary Periods · Life Chapters",
    category: "hellenistic", tags: ["hellenistic", "timing", "periods"],
    summary: "Zodiacal Releasing is one of the most sophisticated timing systems in all of astrology — a nested cycle of planetary periods derived from the Lots, mapping the major chapters, peak periods, and quiet seasons of a life with remarkable precision.",
    chartKeys: [{ type: "technique", key: "currentDasha" }],
    relatedSlugs: ["hellenistic-lot-fortune", "hellenistic-lot-spirit", "hellenistic-profections"],
    promptHint: "Zodiacal releasing: from Lot of Fortune (material life) and Lot of Spirit (agency), Level 1 periods (major eras), Level 2 subperiods, loosings of the bond as peak activation periods, 129-year Taurus-Scorpio cycle.",
  },
  {
    slug: "hellenistic-dignities", title: "Essential Dignities", subtitle: "Domicile · Exaltation · Detriment · Fall",
    category: "hellenistic", tags: ["hellenistic", "strength", "fundamentals"],
    summary: "Essential dignities describe the relative power and comfort of a planet in any given sign. A planet in its domicile or exaltation is strong and effective; a planet in detriment or fall is weakened, operating outside its natural environment.",
    chartKeys: [],
    relatedSlugs: ["hellenistic-sect", "planet-sun", "planet-moon"],
    promptHint: "Essential dignities: domicile (home sign), exaltation (sign of honor), detriment (opposite domicile), fall (opposite exaltation), triplicity lords, bounds/terms, face/decan, how dignity modifies interpretation.",
  },

  // ─── TIMING SYSTEMS ─────────────────────────────────────────────────────────

  {
    slug: "timing-firdaria", title: "Firdaria", subtitle: "Medieval Persian · 75-Year Planetary Cycle",
    category: "timing", tags: ["timing", "periods", "medieval", "persian"],
    summary: "Firdaria is a medieval Arabic–Persian period system that assigns each planet a major reign of years over the course of your life. Like the Vimshottari dasha, it maps which planetary energy governs each chapter — but through the lens of Islamic-era tradition, with distinct sequences for day and night charts.",
    chartKeys: [{ type: "technique", key: "currentFirdaria" }],
    relatedSlugs: ["hellenistic-sect", "hellenistic-releasing", "vedic-vimshottari-dasha"],
    promptHint: "Firdaria: 75-year cycle, day chart order (Sun 10y, Venus 8, Mercury 13, Moon 9, Saturn 11, Jupiter 12, Mars 7, North Node 3, South Node 2), night chart reverses luminaries, sub-periods within each major period.",
  },
  {
    slug: "timing-progressions", title: "Secondary Progressions", subtitle: "One Day = One Year · Symbolic Maturation",
    category: "timing", tags: ["timing", "progressions", "symbolic"],
    summary: "Secondary progressions advance your natal chart one day for every year of your life — a poetic symbolic system where the first day after your birth represents your first year, the second day your second year, and so on. They reveal the slow inner development of the soul.",
    chartKeys: [{ type: "technique", key: "progressions" }],
    relatedSlugs: ["timing-solar-arc", "timing-solar-return", "planet-sun", "planet-moon"],
    promptHint: "Secondary progressions: 1 day = 1 year, progressed Sun changes sign roughly every 30 years, progressed Moon 2.5 years per sign, progressed New Moon as major life chapters, lunation cycle as development arc.",
  },
  {
    slug: "timing-solar-arc", title: "Solar Arc Directions", subtitle: "All Planets Move Together · Year by Degree",
    category: "timing", tags: ["timing", "directions", "solar-arc"],
    summary: "Solar arc directions move every planet in your chart forward by the same amount — the degree the Sun has progressed since your birth. This creates a chart where all planets advance in lockstep, revealing the simultaneous maturation of all life themes at once.",
    chartKeys: [{ type: "technique", key: "progressions" }],
    relatedSlugs: ["timing-progressions", "planet-sun"],
    promptHint: "Solar arc: all planets advance by the same arc (roughly 1° per year), solar arc hits to natal angles as major life events, the uniformity of solar arc vs. the individuality of secondary progressions.",
  },
  {
    slug: "timing-solar-return", title: "Solar Return", subtitle: "Annual Birthday Chart · The Year Ahead",
    category: "timing", tags: ["timing", "annual", "returns"],
    summary: "The Solar Return chart is cast for the exact moment the Sun returns to its natal position each year — your cosmic birthday. It maps the major themes, opportunities, and challenges of the coming year, overlaid on your natal chart.",
    chartKeys: [{ type: "technique", key: "solarReturn" }],
    relatedSlugs: ["planet-sun", "hellenistic-profections", "timing-progressions"],
    promptHint: "Solar return: annual chart cast for Sun's return to natal degree, SR ascendant as the year's dominant theme, SR planets overlaid on natal houses, location of return and its effect, how to read SR in conjunction with profections.",
  },
  {
    slug: "timing-transits", title: "Transits", subtitle: "Current Planetary Positions · Real-Time Triggers",
    category: "timing", tags: ["timing", "transits", "daily"],
    summary: "Transits are the ongoing movements of planets through the sky as they form angles to your natal positions. They are the most immediate timing tool — the daily weather of your cosmic life, ranging from brief Moon transits lasting hours to outer planet conjunctions lasting years.",
    chartKeys: [{ type: "technique", key: "currentDasha" }],
    relatedSlugs: ["planet-saturn", "planet-jupiter", "planet-pluto", "timing-solar-return"],
    promptHint: "Transits: current planets aspecting natal positions, orbs and duration, slow planets (Saturn, Pluto) as major life turners, fast planets as daily weather, how transits trigger natal potential.",
  },

  // ─── VEDIC / JYOTISH ─────────────────────────────────────────────────────────

  {
    slug: "vedic-nakshatra", title: "Nakshatras", subtitle: "27 Lunar Mansions · The Soul's Address",
    category: "vedic", tags: ["vedic", "nakshatra", "lunar-mansion"],
    summary: "The 27 nakshatras divide the zodiac into 13°20′ segments, each with its own deity, quality, and mythological story. Your Moon's nakshatra is considered your soul's deepest fingerprint in Vedic astrology — more revealing than the Sun sign.",
    chartKeys: [{ type: "planet", name: "Moon" }, { type: "planet", name: "Sun" }, { type: "planet", name: "NorthNode" }],
    relatedSlugs: ["vedic-vimshottari-dasha", "vedic-pada", "vedic-lagna"],
    promptHint: "Nakshatras: 27 divisions of 13°20′ each, lunar mansions correlating to Vimshottari dasha lords, each nakshatra has deity, symbol, nature, and motivation (Dharma/Artha/Kama/Moksha), janma nakshatra as birth star.",
  },
  {
    slug: "vedic-pada", title: "Nakshatra Padas", subtitle: "4 Quarters · 108 Cosmic Cells",
    category: "vedic", tags: ["vedic", "nakshatra", "pada"],
    summary: "Each of the 27 nakshatras is divided into 4 padas (quarters) of 3°20′ each, creating 108 cosmic cells that correlate to the Navamsha chart. The pada shows the specific flavor within a nakshatra and maps directly to a zodiac sign in the D9.",
    chartKeys: [{ type: "planet", name: "Moon" }, { type: "planet", name: "Sun" }],
    relatedSlugs: ["vedic-nakshatra", "vedic-varga-d9"],
    promptHint: "Nakshatra padas: 4 quarters of 3°20′ each, 27 × 4 = 108 padas corresponding to the 108 Navamsha positions, each pada ruled by a sign (fire→Aries, earth→Taurus, air→Gemini, water→Cancer cycling), Pushkara Navamshas as blessed padas.",
  },
  {
    slug: "vedic-lagna", title: "Lagna — The Ascendant", subtitle: "Sidereal Rising Sign · The Body in Space",
    category: "vedic", tags: ["vedic", "lagna", "ascendant"],
    summary: "The Lagna is the sidereal ascendant in Jyotish — the sign rising on the eastern horizon at birth, computed against the fixed stars using the Lahiri ayanamsa. It is the most important single point in a Vedic chart, defining the entire house system and the native's bodily constitution.",
    chartKeys: [{ type: "technique", key: "sect" }],
    relatedSlugs: ["vedic-nakshatra", "vedic-varga-d9", "hellenistic-dignities"],
    promptHint: "Lagna: sidereal rising sign, differs from tropical by ~24°, Lagna lord as chart ruler and life significator, Lagna nakshatra as body's fingerprint, angular houses (kendras) counted from Lagna.",
  },
  {
    slug: "vedic-vimshottari-dasha", title: "Vimshottari Dasha", subtitle: "120-Year Planetary Periods · The Life Map",
    category: "vedic", tags: ["vedic", "dasha", "timing"],
    summary: "Vimshottari Dasha is the most widely used timing system in Jyotish — a 120-year cycle of planetary periods determined by the Moon's nakshatra at birth. Each planet rules a major dasha period, and within it, a series of antardasha sub-periods that fine-tune the timing.",
    chartKeys: [{ type: "technique", key: "currentDasha" }],
    relatedSlugs: ["vedic-nakshatra", "vedic-antardasha", "timing-firdaria"],
    promptHint: "Vimshottari Dasha: 120-year cycle, order Ketu(7) Venus(20) Sun(6) Moon(10) Mars(7) Rahu(18) Jupiter(16) Saturn(19) Mercury(17), starting balance determined by Moon's position in nakshatra, dasha lord activates natal promise.",
  },
  {
    slug: "vedic-antardasha", title: "Antardasha", subtitle: "Sub-Periods · The Fine-Tuning of Destiny",
    category: "vedic", tags: ["vedic", "dasha", "timing"],
    summary: "Within each major dasha period, nine antardasha sub-periods cycle through all nine planetary lords in sequence. The antardasha lord modifies and colors the major dasha's themes — bringing its own nature to the fore within the larger chapter.",
    chartKeys: [{ type: "technique", key: "currentDasha" }],
    relatedSlugs: ["vedic-vimshottari-dasha", "vedic-nakshatra"],
    promptHint: "Antardasha: sub-period within a dasha, duration = (sub-ruler years / 120) × major period, antardasha lord aspects and placements modify the dasha promise, pratyantar dasha (sub-sub-periods) for even finer timing.",
  },
  {
    slug: "vedic-chara-karakas", title: "Jaimini Chara Karakas", subtitle: "Soul Significators · Ranked by Degree",
    category: "vedic", tags: ["vedic", "jaimini", "karakas"],
    summary: "The Jaimini Chara Karakas are seven (or eight) planetary significators ranked by their degree within their sign. The planet with the highest degree becomes the Atmakaraka — the soul significator — and holds the most revelatory position in the entire chart for questions of purpose and destiny.",
    chartKeys: [{ type: "technique", key: "ak" }],
    relatedSlugs: ["vedic-atmakaraka", "vedic-varga-d9"],
    promptHint: "Jaimini Chara Karakas: 7 planets ranked by degree within sign (highest to lowest) → AK Atmakaraka, AmK Amatyakaraka, BK Bhratrikaraka, MK Matrikaraka, PK Pitrikaraka, GK Gnatikaraka, DK Darakaraka. Rahu uses 30° - degree.",
  },
  {
    slug: "vedic-atmakaraka", title: "Atmakaraka (AK)", subtitle: "Soul's Planet · The Deepest Significator",
    category: "vedic", tags: ["vedic", "jaimini", "karakas", "soul"],
    summary: "The Atmakaraka is the planet with the highest degree in its sign across the chart — the soul's significator, showing the deepest desire the soul carries into this incarnation. Its placement, nakshatra, and navamsha position are the most revealing factors for the soul's path.",
    chartKeys: [{ type: "technique", key: "ak" }],
    relatedSlugs: ["vedic-chara-karakas", "vedic-varga-d9"],
    promptHint: "Atmakaraka: highest degree planet = soul ruler, its sign and house shows where the soul seeks fulfillment, AK in D9 Navamsha shows the soul's dharmic direction, AK's nakshatra as the soul's deepest nature.",
  },
  {
    slug: "vedic-varga-d9", title: "Navamsha (D9)", subtitle: "The Soul Chart · Marriage & Inner Nature",
    category: "vedic", tags: ["vedic", "varga", "divisional", "navamsha"],
    summary: "The Navamsha is the most important divisional chart in Jyotish after the D1 natal chart — the soul chart that reveals inner nature, dharma, and the quality of partnerships. A strong D1 placement confirmed in D9 is fully empowered; a weak D9 undermines apparent strength.",
    chartKeys: [{ type: "technique", key: "ak" }],
    relatedSlugs: ["vedic-pada", "vedic-chara-karakas", "vedic-varga-d10"],
    promptHint: "Navamsha D9: 9 divisions of each sign (3°20′), trikonastha calculation rule (fire→Aries, earth→Capricorn, air→Libra, water→Cancer), Pushkara Navamsha as specially fortunate, Vargottama when D1 and D9 sign match.",
  },
  {
    slug: "vedic-varga-d10", title: "Dasamsha (D10)", subtitle: "Career Chart · Public Achievement",
    category: "vedic", tags: ["vedic", "varga", "divisional", "career"],
    summary: "The Dasamsha is the chart of career and public achievement in Jyotish. The 10th house in D1 shows the native's calling; the D10 Lagna and its ruler reveal the specific arena of professional life and the quality of recognition the native receives.",
    chartKeys: [{ type: "house", number: 10 }],
    relatedSlugs: ["house-10th", "vedic-varga-d9", "planet-saturn"],
    promptHint: "Dasamsha D10: 10 divisions of 3° each, general Parashari formula, D10 Lagna lord as career significator, planets in D10 1st/10th houses as career activators, how D10 confirms or contradicts D1 10th house.",
  },
  {
    slug: "vedic-rahu-ketu", title: "Rahu & Ketu", subtitle: "☊ ☋ · The Lunar Nodes · Karma's Axis",
    category: "vedic", tags: ["vedic", "nodes", "karma"],
    summary: "Rahu (North Node) and Ketu (South Node) are the shadow planets of Vedic astrology — always exactly opposite each other, they mark the axis of karmic evolution. Rahu hungers for the new and unexperienced; Ketu has mastered and must release.",
    chartKeys: [{ type: "planet", name: "NorthNode" }],
    relatedSlugs: ["vedic-vimshottari-dasha", "vedic-chara-karakas"],
    promptHint: "Rahu: obsession, materialism, foreign influence, the dragon's head, amplifies the sign/house it occupies. Ketu: spirituality, liberation, past-life mastery, the dragon's tail. Rahu dasha (18 years) as major worldly ambition period.",
  },
  {
    slug: "vedic-ayanamsa", title: "Ayanamsa & Sidereal Zodiac", subtitle: "The Zodiac's Precession · Lahiri vs. Tropical",
    category: "vedic", tags: ["vedic", "sidereal", "ayanamsa", "fundamentals"],
    summary: "The ayanamsa is the degree of separation between the tropical and sidereal zodiacs — currently about 24°. Vedic astrology uses the sidereal zodiac (fixed against the stars), while Western astrology uses the tropical zodiac (fixed to the equinoxes). Your sidereal placements are typically 1–2 signs earlier than your tropical ones.",
    chartKeys: [{ type: "technique", key: "sect" }],
    relatedSlugs: ["vedic-lagna", "vedic-nakshatra"],
    promptHint: "Ayanamsa: precession of the equinoxes, currently ~24°, Lahiri (Chitrapaksha) as the official Indian government standard, different schools use different ayanamsas, tropical vs. sidereal practical difference in chart interpretation.",
  },

  // ─── ESOTERIC ────────────────────────────────────────────────────────────────

  {
    slug: "esoteric-arabic-parts", title: "Arabic Parts / Lots", subtitle: "Sensitive Points · Derived from Three Factors",
    category: "esoteric", tags: ["esoteric", "hellenistic", "arabic-parts"],
    summary: "The Arabic Parts (also called Hermetic Lots) are mathematical points derived from three chart factors — usually two planets plus the Ascendant. There are over 100 lots, each describing a specific life domain, with Fortune and Spirit being the most important.",
    chartKeys: [],
    relatedSlugs: ["hellenistic-lot-fortune", "hellenistic-lot-spirit"],
    promptHint: "Arabic parts: mathematical sensitive points, the seven Hermetic Lots (Fortune, Spirit, Necessity, Eros, Courage, Victory, Nemesis), Lot of Marriage, Lot of Children, how sect reversal works for night charts.",
  },
  {
    slug: "esoteric-fixed-stars", title: "Fixed Stars", subtitle: "Stellar Lore · Ancient Sky Markers",
    category: "esoteric", tags: ["esoteric", "fixed-stars"],
    summary: "Fixed stars are the background stars of the sky that conjunct sensitive points in the natal chart, adding specific archetypal flavors. Unlike planets, they barely move — a planet conjunct Algol, Regulus, or Aldebaran carries millennia of accumulated meaning.",
    chartKeys: [],
    relatedSlugs: ["planet-sun", "planet-moon", "house-10th"],
    promptHint: "Fixed stars: parans and conjunctions within 1°, the royal stars (Regulus, Aldebaran, Antares, Fomalhaut), malefic stars (Algol, Caput Algol), how fixed star conjunctions modify natal planetary meaning.",
  },
  {
    slug: "esoteric-out-of-bounds", title: "Out of Bounds Planets", subtitle: "Beyond the Sun's Declination · Wild Energy",
    category: "esoteric", tags: ["esoteric", "declination", "out-of-bounds"],
    summary: "A planet is Out of Bounds (OOB) when its declination exceeds the Sun's maximum of 23°27′. OOB planets operate beyond the Sun's reach — unconstrained, extreme, and often exceptional. They can indicate genius, transgression, or an energy that simply refuses to play by the rules.",
    chartKeys: [],
    relatedSlugs: ["planet-moon", "planet-mercury", "planet-venus"],
    promptHint: "Out of Bounds: declination beyond ±23°27′, Moon OOB as emotional extremes, Mercury OOB as unconventional thinking, Venus OOB as unusual relationships, historical peaks of OOB planets and their effects.",
  },
  {
    slug: "esoteric-antiscia", title: "Antiscia", subtitle: "Mirror Points · Solstice Axis Reflections",
    category: "esoteric", tags: ["esoteric", "antiscia", "mirror"],
    summary: "Antiscia are mirror-point positions reflected across the Cancer-Capricorn solstice axis. Two planets in antiscia — whose degrees add up to 30° in their respective signs — are in a secret conjunction, communicating across the chart in a hidden but powerful way.",
    chartKeys: [],
    relatedSlugs: ["hellenistic-sect"],
    promptHint: "Antiscia: reflection across 0° Cancer/0° Capricorn, antiscion formula (30 - sign degree in mirror sign), contra-antiscia (reflection across Aries/Libra equinox), how to find antiscia by sign pairs (Aries↔Pisces, Taurus↔Aquarius, Gemini↔Capricorn, Cancer↔Sagittarius, Leo↔Scorpio, Virgo↔Libra).",
  },
  {
    slug: "esoteric-sabian-symbols", title: "Sabian Symbols", subtitle: "360 Degrees · One Image Per Degree",
    category: "esoteric", tags: ["esoteric", "sabian", "degree-symbolism"],
    summary: "The Sabian Symbols are a set of 360 channeled images — one for each degree of the zodiac — created by clairvoyant Elsie Wheeler in 1925. Each natal planet's degree carries a specific symbolic image that adds poetic depth to its meaning in the chart.",
    chartKeys: [],
    relatedSlugs: ["planet-sun", "planet-moon", "house-1st"],
    promptHint: "Sabian symbols: 360 channeled images by Elsie Wheeler and Marc Edmund Jones (1925), how to find the symbol for any natal planet (round up to next degree), archetypal images and their interpretive keywords, using Sabians for depth not literalism.",
  },
];

export const ENTRIES_BY_SLUG = Object.fromEntries(
  AKASHIC_ENTRIES.map(e => [e.slug, e])
);

export const ENTRIES_BY_CATEGORY = AKASHIC_ENTRIES.reduce<Record<string, AkashicEntry[]>>(
  (acc, e) => { (acc[e.category] ??= []).push(e); return acc; },
  {}
);
